services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8001:80"
    volumes:
      - .:/src
    environment:
      - ENVIRON=prd
      - TIMEZONE=America/Sao_Paulo
      - HOST_VITI_BRASIL=http://vitibrasil.cnpuv.embrapa.br
      - PATH_DATABASE_VITIDATA=src/database/vitidata.db
      - USERNAME_API=fiap
      - PASSWORD_API=fiap
    command: python main.py
#    depends_on:
#      - postgres

#  postgres:
#    image: postgres:14-alpine
#    ports:
#      - "5432:5432"
#    volumes:
#      - ~/apps/postgres:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PASSWORD=vert
#      - POSTGRES_USER=vert
#      - POSTGRES_DB=vert_db

networks:
  default:
    driver: bridge
